### ISSUE TITLE
[BUG] lint script broken

### ISSUE THREAD

**Issue by rotu** [npm/template-oss#359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`npm run lint`

```
> @npmcli/template-oss@4.18.0 lint
> eslint "**/*.js"


Oops! Something went wrong! :(

ESLint: 8.49.0

Error: ESLint configuration in test\apply\tap-testdir-files-snapshots-turn-off-specific-files\.eslintrc.yml is invalid:
        - Property "" is the wrong type (expected object but got `"exists"`).

    at ConfigValidator.validateConfigSchema (C:\Users\dan\Source\template-oss\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2168:19)
    at ConfigArrayFactory._normalizeConfigData (C:\Users\dan\Source\template-oss\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3010:19)
    at ConfigArrayFactory.loadInDirectory (C:\Users\dan\Source\template-oss\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2878:33)
    at CascadingConfigArrayFactory._loadConfigInAncestors (C:\Users\dan\Source\template-oss\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3860:46)
    at CascadingConfigArrayFactory.getConfigArrayForFile (C:\Users\dan\Source\template-oss\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3781:18)
    at FileEnumerator._iterateFilesRecursive (C:\Users\dan\Source\template-oss\node_modules\eslint\lib\cli-engine\file-enumerator.js:450:49)
    at _iterateFilesRecursive.next (<anonymous>)
    at FileEnumerator._iterateFilesRecursive (C:\Users\dan\Source\template-oss\node_modules\eslint\lib\cli-engine\file-enumerator.js:497:33)
    at _iterateFilesRecursive.next (<anonymous>)
    at FileEnumerator._iterateFilesRecursive (C:\Users\dan\Source\template-oss\node_modules\eslint\lib\cli-engine\file-enumerator.js:497:33)
```

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node:
- OS: Windows 11
- platform:

**Comment by rotu** [comment]
This seems to happen if you run `npx tap -- --save-fixture`. It is not fixed by simply adding `tap-testdir*/` to .gitignore per #350.
